# Server
server:
  port: 8084

spring:
  application:
    name: notification-service

  # Disable Config Server
  cloud:
    config:
      enabled: false
    gcp:
      core:
        enabled: false
      firestore:
        enabled: false
  # MongoDB
  data:
    mongodb:
      host: localhost
      port: 27017
  # Kafka
  kafka:
    consumer:
      bootstrap-servers: localhost:9002
      group-id: notificationGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: donationEvent:com.greengrub.notification.dto.Donation
    listener:
      missing-topics-fatal: false
  # Mail
  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:1025}
    username: ${MAIL_USERNAME:admin}
    password: ${MAIL_PASSWORD:password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  # Thymeleaf
  thymeleaf:
    cache: false
  # Exclude Firestore auto-config in local profile
  autoconfigure:
    exclude:
      - com.google.cloud.spring.autoconfigure.firestore.GcpFirestoreAutoConfiguration
      - com.google.cloud.spring.autoconfigure.firestore.FirestoreRepositoriesAutoConfiguration
      - com.google.cloud.spring.autoconfigure.firestore.FirestoreTransactionManagerAutoConfiguration

# Resilience4j
resilience4j:
  retry:
    instances:
      notificationRetry:
        max-attempts: 3
        wait-duration: 500ms
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
  circuitbreaker:
    instances:
      notificationBreaker:
        failure-rate-threshold: 50
        sliding-window-size: 10
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 3
        register-health-indicator: true

# Logging
logging:
  level:
    root: INFO
    com.greengrub: DEBUG          # or INFO in production
    org.springframework: INFO
    net.logstash.logback.appender: ERROR
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,loggers
  endpoint:
    prometheus:
      enabled: true

eureka:
  client:
    enabled: true