# ──────────────────────────────────────────────────────────────────────────────
# PRIVATE — DO NOT COMMIT TO GIT
# Customer Service Secret  –  apply manually inside the cluster
# kubectl apply -f customer-service-secret.yaml -n services
# ──────────────────────────────────────────────────────────────────────────────
apiVersion: v1
kind: Secret
metadata:
  name: customer-service-secret
  namespace: services
type: Opaque
stringData:
  DB_USERNAME:           "<your-db-username>"
  DB_PASSWORD:           "<your-db-password>"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://<cloud-sql-public-ip>:5432/<db-name>"
  JWT_SECRET:            "<min-64-char-random-secret-for-HS256>"
  JWT_EXPIRATION:        "86400000"
