# Server configuration
server.port=8761
spring.application.name=discovery-service

# Standalone Eureka server settings
eureka.instance.hostname=localhost

# Tells this instance NOT to register itself as a client
eureka.client.register-with-eureka=false

# Tells this instance NOT to pull a registry cache from other instances
eureka.client.fetch-registry=false

# Sets the local zone registry path
eureka.client.service-url.defaultZone=http://${eureka.instance.hostname}:${server.port}/eureka/

# Optional: Disables self-preservation mode (ideal for local development workflows)
eureka.server.enable-self-preservation=false