spring.application.name=image-service
grpc.server.address=9090

gcp.bucket.name=your-actual-bucket-name

# Standalone H2 database
spring.datasource.url=jdbc:h2:mem:fooddb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=